# Generated by Django 4.1.2 on 2022-10-16 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('full_path', models.FileField(upload_to='user_uploads/%Y/%m/%d/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='accounts.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
